spring:
  application:
    name: awsome
  messages:
    basename: i18n/messages

server:
  port: 8088

logging:
  level:
    org.startlight.awsome: DEBUG

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
